environment:
    PYTHON: "C:\\Python36"
    PATH: "C:\\Python36;C:\\Python36\\Scripts;%PATH%"
install:
    - python -m ensurepip
    - pip install tox
build_script:
    - python --version
test_script:
    - tox -e windows
